spring:
  application:
      name: client


server:
  port: 8076


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:WannaBeIn3ureka@localhost:8761/eureka/